# Generated by Django 2.2.5 on 2020-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_uel',
            new_name='project_url',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='description', null=True),
        ),
    ]
