# Generated by Django 2.2.5 on 2020-03-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200330_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('mid-level', 'Mid-Level'), ('advanced', 'Advanced')], max_length=120)),
            ],
        ),
    ]
