# Generated by Django 2.2.5 on 2020-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200330_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 25), ('mid-level', 50), ('intermediate', 65), ('advanced', 90)], max_length=120),
        ),
    ]
